title: Generative Art Experiments
author: Avi
copyright                   : "2023"

execute:
  execute_notebooks: 'off'

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/avivajpeyi/ihaka_generative_art_2023
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repoitory_button: true
  favicon: https://raw.githubusercontent.com/avivajpeyi/dev_site/main/assets/media/icon.png


sphinx:
  extra_extensions:
   - sphinx_panels